services:
  # 1. Nasza baza danych
  postgres-db:
    image: postgres:15-alpine
    container_name: sit-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-selfimprovement}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-haslo}
    ports:
      - "5432:5432"
    volumes:
      - sit_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-selfimprovement}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: sit-backend:1.1
    container_name: sit-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${DB_NAME:-selfimprovement}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:haslo}
      SPRING_MAIL_USERNAME: ${GMAIL_USER}
      SPRING_MAIL_PASSWORD: ${GMAIL_APP_PASSWORD}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY} 
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  sit_pg_data: